@baseUrl = http://localhost:3100
@todoId = 123e4567-e89b-12d3-a456-426614174000
@userId = 1
@polygonId = 1

###
# Health Check
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Service is healthy",
#   "responseObject": null,
#   "statusCode": 200
# }
GET {{baseUrl}}/health-check

###
# Get Users
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Users retrieved successfully",
#   "responseObject": [ /* array of users */ ],
#   "statusCode": 200
# }
GET {{baseUrl}}/users

###
# Get User by ID
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "User retrieved successfully",
#   "responseObject": { /* user object */ },
#   "statusCode": 200
# }
GET {{baseUrl}}/users/{{userId}}

###
# Create Todo
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Todo created successfully",
#   "responseObject": { /* new todo object */ },
#   "statusCode": 201
# }
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "text": "Learn API Testing",
  "isDone": false
}

###
# Get Todos
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Todos retrieved successfully",
#   "responseObject": [ /* array of todos */ ],
#   "statusCode": 200
# }
GET {{baseUrl}}/todos

###
# Get Todo by ID
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Todo retrieved successfully",
#   "responseObject": { /* todo object */ },
#   "statusCode": 200
# }
GET {{baseUrl}}/todos/{{todoId}}

###
# Update Todo by ID
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Todo updated successfully",
#   "responseObject": { /* updated todo object */ },
#   "statusCode": 200
# }
PUT {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json

{
  "text": "Master API Testing",
  "isDone": true
}

###
# Delete Todo by ID
# Expected: Empty body, Status 204 No Content
DELETE {{baseUrl}}/todos/{{todoId}}

###
# Create Polygon
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Polygon created successfully",
#   "responseObject": {
#     "id": "uuid",
#     "name": "P1",
#     "points": [{"x": 12.3, "y": 12.0}, {"x": 16.3, "y": 12.0}, {"x": 16.3, "y": 8.0}, {"x": 12.3, "y": 8.0}],
#     "created_at": "2025-06-28T09:00:00.000Z"
#   },
#   "statusCode": 201
# }
POST {{baseUrl}}/polygons
Content-Type: application/json

{
  "name": "P1",
  "points": [{"x": 12.3, "y": 12.0}, {"x": 16.3, "y": 12.0}, {"x": 16.3, "y": 8.0}, {"x": 12.3, "y": 8.0}]
}

###
# Get All Polygons
# Expected ServiceResponse:
# {
#   "success": true,
#   "message": "Polygons retrieved successfully",
#   "responseObject": [ /* array of polygons */ ],
#   "statusCode": 200
# }
GET {{baseUrl}}/polygons

###
# Delete Polygon by ID
# Expected: Empty body, Status 204 No Content
DELETE {{baseUrl}}/polygons/{{polygonId}}